apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o k8s_new
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o k8s_new
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: django
    spec:
      containers:
        - args:
            - uwsgi
            - --socket
            - :8001
            - --module
            - app.wsgi
            - --py-autoreload
            - "1"
            - --logto
            - /tmp/mylog.log
            - --enable-threads
            - --single-interpreter
            - --master
            - --lazy-apps
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: django--env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: django--env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: django--env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: django--env
          image: django_uwsgi:1.0.0
          name: django-uwsgi-django
          ports:
            - containerPort: 8001
          resources: {}
          volumeMounts:
            - mountPath: /code
              name: django-hostpath0
            - mountPath: /static
              name: django-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/turbou/Documents/git/ContrastSecurity/agent/python/django_uwsgi_nginx_docker/src
          name: django-hostpath0
        - hostPath:
            path: /Users/turbou/Documents/git/ContrastSecurity/agent/python/django_uwsgi_nginx_docker/static
          name: django-hostpath1
status: {}
