apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o k8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o k8s
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: django
    spec:
      containers:
        - args:
            - uwsgi
            - --socket
            - :8001
            - --module
            - app.wsgi
            - --py-autoreload
            - "1"
            - --logto
            - /tmp/mylog.log
            - --enable-threads
            - --single-interpreter
            - --master
            - --lazy-apps
          env:
            - name: TZ
              value: Asia/Tokyo
          image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/django_uwsgi_django:1.0.0
          imagePullPolicy: Always
          name: django-uwsgi-django
          ports:
            - containerPort: 8001
          resources: {}
          volumeMounts:
            - mountPath: /static
              name: django-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /tmp/static
          name: django-hostpath0
status: {}
