apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o k8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o k8s
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Tokyo
          image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/django_uwsgi_nginx:1.0.0
          imagePullPolicy: Always
          name: django-uwsgi-nginx
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /static
              name: nginx-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /tmp/static
          name: nginx-hostpath0
status: {}
