version: '3'

services:
# mysql container

  mail:
    image: mailhog/mailhog:v1.0.1
    container_name: mail
    environment:
      - MH_UI_WEB_PATH=mail

  mysql:
    image: mysql:8.0.21
    #image: arm64v8/mysql:8.0.32
    container_name: mysql
    command: --log-bin-trust-function-creators=ON
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=contrast
      - MYSQL_USER=contrast
      - MYSQL_PASSWORD=default1!
    ports:
      - '3306'

# Teamserver container
  contrast:
    image: ghcr.io/contrast-security-inc/contrast:latest
    #image: ghcr.io/contrast-security-inc/contrast:3.9.11.3941630875@sha256:f5c38a1cd679fa71ea0af3ca2a960ea4a7261f4756e1c1cfe0240d7d3b9c25ad
    container_name: teamserver
    depends_on:
      - mail
      - mysql
    ports:
      - 8080:8080
    environment:
    # LICENCE Setup:
      - CONTRAST_LICENSE=${CONTRAST_LICENSE}   #loaded via ENV
      # Use Hub account to pull license
      # - CONTRAST_HUB_USERNAME=<EMAIL>
      # - CONTRAST_HUB_PASSWORD=<PASSWORD>
    # MySQL Setup: 
      # FOR REMOTE MySQL
      # - CONTRAST_JDBC_URL=jdbc:mysql://<DNS of MYSQL>:3306/contrast
      # - CONTRAST_JDBC_USER=contrast
      # - CONTRAST_JDBC_PASS=<PASSWORD>
      # FOR LOCALHOST MySQL
      # - CONTRAST_JDBC_URL=jdbc:mysql://host.docker.internal:3306/contrast
      # - CONTRAST_JDBC_USER=contrast
      # - CONTRAST_JDBC_PASS=<PASSWORD>
      # For a MySQL Container  --Uncomment 6 thru 15 and 20 & 21 along with the lines below.
      - CONTRAST_JDBC_URL=jdbc:mysql://mysql:3306/contrast
      - CONTRAST_JDBC_USER=contrast
      - CONTRAST_JDBC_PASS=default1!
    # SAML Setup
      # - CONTRAST_AUTHENTICATOR_SAML_KEYSTORE_PASSWORD=changeit
      # - CONTRAST_AUTHENTICATOR_SAML_KEYSTORE_PASSWORDMAP=some-alias=changeit
    volumes:
      - ./contrast_conf:/opt/contrast/conf
    deploy: 
      resources:
        limits:
          cpus: "2.0"
          memory: 8g
        reservations:
          cpus: "1.0"
          memory: 4g

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    depends_on:
      - contrast
    ports:
      - 80:80
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d

