version: '3.7'

services:
  nginx:
    container_name: dvwa.nginx
    image: nginx:1.10
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d
      - ./html:/var/www/html
    depends_on:
      - php

  php:
    container_name: dvwa.php
    build:
      context: .
    volumes:
      - ./html:/var/www/html
      - ./docker/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./contrast_security.yaml:/etc/contrast/contrast_security.yaml
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: dvwa.mysql
    environment:
      - "MYSQL_USER=dvwa"
      - "MYSQL_PASSWORD=p@ssw0rd"
      - "MYSQL_DATABASE=dvwa"
      - "MYSQL_ROOT_PASSWORD=buhihi"

