version: '3'

services:
  nginx:
    image: nginx:1.13
    container_name: relay.nginx
    restart: always
    ports:
      - "8087:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./relay_django/static:/usr/share/nginx/html/static
    depends_on:
      - django

  django:
    image: relay-django:1.0.6
    build:
      context: ./django
    container_name: relay.django
    restart: always
    command: python /project/django_project/manage.py runserver 0.0.0.0:8081
    volumes:
      - ./relay_django:/project/django_project
    expose:
      - "8081"
    depends_on:
      - redis

  redis:
    image: redis:6.2.5-alpine3.14
    container_name: relay.redis
    restart: always
    depends_on:
      - postgres

  celery:
    image: relay-django:1.0.6
    build:
      context: ./django
    container_name: relay.celery
    restart: always
    command: celery -A relay_django worker -l info
    volumes:
      - ./relay_django/:/project
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  celery-beat:
    image: relay-django:1.0.6
    build:
      context: ./django
    container_name: relay.celery-beat
    restart: always
    command: celery -A relay_django beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./relay_django/:/project
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  postgres:
    image: postgres:9.4.23
    container_name: relay.postgres
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:4.18
    container_name: relay.pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    hostname: pgadmin4
    restart: always
    depends_on:
      - postgres

