version: '3'

services:
  nginx:
    image: nginx:1.13
    container_name: relay.nginx
    restart: always
    ports:
      - "8087:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./relay_django/static:/usr/share/nginx/html/static
    depends_on:
      - django

  django:
    image: django:1.0.5
    build:
      context: ./django
    container_name: relay.django
    restart: always
    command: python /project/django_project/manage.py runserver 0.0.0.0:8081
    volumes:
      - ./relay_django:/project/django_project
    expose:
      - "8081"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.4.23
    container_name: relay.postgres
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:4.18
    container_name: relay.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    hostname: pgadmin4
    restart: always

