version: '3'

services:
  nginx:
    image: django_uwsgi_nginx:1.0.0
    build: ./nginx
    container_name: django_uwsgi_nginx
    ports:
      - "8000:8000"
    environment:
     - TZ=Asia/Tokyo
    volumes:
      - ./static:/static
    depends_on:
      - django
    labels:
      kompose.image-pull-policy: "IfNotPresent"
      kompose.service.type: loadbalancer

  django:
    image: django_uwsgi_django:1.0.0
    build: ./django
    container_name: django_uwsgi_django
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log --enable-threads --single-interpreter --master --lazy-apps
    expose:
      - "8001"
    environment:
     - TZ=Asia/Tokyo
    volumes:
      - ./static:/static
    labels:
      kompose.image-pull-policy: "IfNotPresent"

