version: '3.7'

services:
  mysql:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "drupal"
    ports:
      - "3306:3306"

  drupal:
    build: ./
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  data: {}
