apiVersion: v1
kind: Service
metadata:
  name: contrast
  labels:
    app: contrast
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: sticky
spec:
  type: NodePort
  selector:
    app: contrast
  ports:
    - protocol: TCP
      port: 28000
      targetPort: 8080
      nodePort: 30000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: contrast
  labels:
    app: contrast
spec:
  selector:
    matchLabels:
      app: contrast
  serviceName: "contrast"
  replicas: 1
  template:
    metadata:
      labels:
        app: contrast
    spec:
      hostNetwork: true
      containers:
        - name: contrast
          image: ghcr.io/contrast-security-inc/contrast:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: CONTRAST_JDBC_URL
              value: "jdbc:mysql://192.168.100.16/contrast"
            - name: CONTRAST_JDBC_USER
              value: "contrast"
            - name: CONTRAST_JDBC_PASS
              valueFrom:
                secretKeyRef:
                  name: contrast-database
                  key: password
            - name: CONTRAST_LICENSE
              valueFrom:
                secretKeyRef:
                  name: contrast-license
                  key: license
                
            - name: JAVA_OPTS
              value: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=50.0 -XX:MinRAMPercentage=30.0"
          livenessProbe:
            httpGet:
              path: /Contrast/api/public/ng/health/status/live
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 30
            failureThreshold: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /Contrast/api/public/ng/health/status/ready
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 30
            failureThreshold: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: contrast-config-volume
              mountPath: /opt/contrast/conf
            - name: data
              mountPath: /opt/contrast/data
            - name: agents
              mountPath: /opt/contrast/data/agents
          resources:
            requests:
              cpu: 1.0
              memory: 2Gi
            limits:
              cpu: 2.0
              memory: 4Gi
      initContainers:
        - name: init-migrations
          image: ghcr.io/contrast-security-inc/contrast:latest
          env:
            - name: CONTRAST_JDBC_URL
              value: "jdbc:mysql://192.168.100.16/contrast"
            - name: CONTRAST_JDBC_PASS
              valueFrom:
                secretKeyRef:
                  name: contrast-database
                  key: password
            - name: CONTRAST_JDBC_USER
              value: "contrast"
            - name: CONTRAST_LICENSE
              valueFrom:
                secretKeyRef:
                  name: contrast-license
                  key: license
          args: ['run-migrations.sh']
        - name: init-agents
          image: ghcr.io/contrast-security-inc/contrast:latest
          command: ["/bin/sh", "-c"]
          args: ["cp -rf /opt/contrast/data/agents/. /mnt/agents/"]
          volumeMounts:
            - name: agents
              mountPath: /mnt/agents
      volumes:
        - name: contrast-config-volume
          configMap:
            name: contrast-config
            optional: true
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
  - metadata:
      name: agents
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
